### ISSUE TITLE
Nana master doesn't build on Visual Studio 2017

### ISSUE THREAD

**Issue by TBBle** [FelixPetriconi/accu2017setup#2]
The develop branch of nana has cnjinhao/nana@e7181a700783867da86553c3e103d858f9eb99e6 which fixes the build for Visual Studio 2017, and needs to be cherry-picked.

Reference is https://connect.microsoft.com/VisualStudio/Feedback/Details/1403302 which indicates that the codecvt issue could not be fixed for VS2017 to maintain binary compatibility.

**Comment by FelixPetriconi** [comment]
Thanks for reporting it. I just fixed it.
